### PR TITLE
feat(price-feed): adds CoinGeckoPriceFeed as another source for querying DAI:PHP quote

### PR DESCRIPTION
**Pull request by schystz**
### Important Note: <br />This PR contains changes from PR#1 so please let's review & close that one first before proceeding to this PR

**Motivation**

This will serve as another source for quoting DAI:PHP price, aside from the previously added CoinMarketCapFeed. We can then use both price feeds in the MedianizerPriceFeed to get the final price.

**Summary**

First, CoinGeckoPriceFeed.js is added which is based from CoinMarketCapPriceFeed.js. Then we updated CreatePriceFeed.js to add another option for CoinGeckoPriceFeed. We also added a new test (CoinGeckoPriceFeed.js) and updated CreatePriceFeed.js test to make sure the new changes works and doesn't break anything.

**Details**

For the historical price, we simply store the time-price value pair every time update() is called, which is a different approach from CryptoWatchPriceFeed since it uses another API call to fetch the history. This is because CoinGecko lacks a price history API.

**Testing**

Check a box to describe how you tested these changes and list the steps for reviewers to test.

- [ ]  Ran end-to-end test, running the code as in production
- [x]  New unit tests created
- [ ]  Existing tests adequate, no new tests required
- [ ]  All existing tests pass
- [ ]  Untested

To test the changes, simply cd to `packages/financial-templates-lib` then run the below test script:

```
npx hardhat test test/price-feed/CoinGeckoPriceFeed.js test/price-feed/CreatePriceFeed.js

// or to test everything from financial-templates-lib package:
yarn truffle test --network test
```

**Issue(s)**

https://lifemesh.atlassian.net/browse/BGM-572

### CODE REVIEW

**Comment by chris247474** [comment]
Screen Shot 2021-01-29 at 10 23 08 AM

@schystz has this ever happened to you when running only specific tests? this doesnt happen to me in our other repos though. `yarn truffle test --network test` seems to work (its a bit long, still waiting for it to finish atm)

Another thing, I guess you meant `npx hardhat test test/price-feed/CoinGeckoPriceFeed.js` rather than referring to coinmarketcappricefeed.js in the hardhat test command in the description :)

**Comment by schystz** [comment]
> Screen Shot 2021-01-29 at 10 23 08 AM
> 
> @schystz has this ever happened to you when running only specific tests? this doesnt happen to me in our other repos though. `yarn truffle test --network test` seems to work (its a bit long, still waiting for it to finish atm)
> 
> Another thing, I guess you meant `npx hardhat test test/price-feed/CoinGeckoPriceFeed.js` rather than referring to coinmarketcappricefeed.js in the hardhat test command in the description :)

Oh yeah, thanks for spotting that out @ctverceles!

I had to install hardhat inside the `packages/financial-templates-lib` using `npm i hardhat` for the test script to work - I'm not sure why is that so and also unsure how UMA test this package only.

**Comment by chris247474** [comment]
@schystz ok working now! pls merge when good

**Comment by chris247474** [comment]
feel free not to close the branch so you can copy over to UMA's protocol master PR. pls link to this issue https://github.com/UMAprotocol/protocol/issues/2474? @schystz

**Comment by schystz** [comment]
> feel free not to close the branch so you can copy over to UMA's protocol master PR. pls link to this issue [UMAprotocol#2474](https://github.com/UMAprotocol/protocol/issues/2474)? @schystz

Ok will do that. Merging now!

**Pull request merged**
